export const THRESHOLDS = {
  RISK_REFUSE: 90,
  RISK_ESCALATE: 70,
  RISK_ASK_DEFER_MODERATE: 50,
  RISK_ELEVATED: 30,
  CONFIDENCE_LOW: 70,
  OFF_HOURS_END: 6,
  OFF_HOURS_START: 22,
  MAX_RISK: 100,
  MAX_CONFIDENCE: 100,
  MIN_CONFIDENCE: 0
};
